[package]
name = "api-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core-domain = { workspace = true }
core-schema = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
chrono = { workspace = true }
