[package]
name = "services"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core-domain = { workspace = true }
core-schema = { workspace = true }
api-types = { workspace = true }
db = { workspace = true }
dynamic-store = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
regex = { workspace = true }
once_cell = { workspace = true }
sea-orm = { workspace = true }
sea-query = { workspace = true }
arc-swap = "1"
jsonwebtoken = { workspace = true }
argon2 = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
sea-orm-migration = { workspace = true }
