#!/usr/bin/env python3
"""Re-apply local customizations to the cargo-dist generated release workflow.

`.github/workflows/release.yml` is generated by cargo-dist. We customize it
because the release is prepared by release-plz, whose tags are pushed with the
default `GITHUB_TOKEN` and therefore do not trigger workflows:

  1. Add a `workflow_dispatch` trigger with a `tag` input, so the Release-plz
     workflow can dispatch this workflow explicitly. The tag is passed as an
     input (instead of dispatching on the tag ref) because workflows are always
     read from the ref they are dispatched on, and the workflow file stored at
     an old tag's commit has no `workflow_dispatch` trigger.
  2. Restrict the tag trigger to the tags we actually publish, and keep the
     `pull_request` trigger (dist only runs `plan` there).
  3. Use the dispatched tag (falling back to the tag ref) to select what dist
     builds and check out that tag's source, and only publish for real release
     runs (tag push or a dispatch carrying `tag`).

Usage (after `dist generate --mode ci`):

    python3 scripts/patch_release_workflow.py [path/to/release.yml]

`dist-workspace.toml` sets `allow-dirty = ["ci"]` so cargo-dist accepts the
difference between this file and its template; re-run this script whenever the
workflow is regenerated.
"""

from __future__ import annotations

import sys
from pathlib import Path

DEFAULT_PATH = Path(".github/workflows/release.yml")

ON_BLOCK = """on:
  pull_request:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
"""

ON_BLOCK_PATCHED = """on:
  # NOTE: manual edits below are re-applied by
  # `python3 scripts/patch_release_workflow.py` after `dist generate`.
  #
  # Dispatched by the Release-plz workflow after it created the `v<version>`
  # tag for a new release: tags created with the default GITHUB_TOKEN do not
  # trigger workflows. The release tag is passed as an input because workflows
  # are read from the dispatched ref, and the workflow file stored at an old
  # tag's commit may predate this trigger.
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to publish (must already exist), e.g. v0.3.1"
        required: false
        type: string
  # Run on pull requests too (`dist plan` only, nothing is published) so the
  # release PR exercises the same workflow that publishes the binaries.
  pull_request:
  push:
    tags:
      # Only the single application tag (`v<version>`) publishes a release.
      # release-plz's per-package `<crate>-v<version>` tags are internal (they
      # carry no GitHub Release) and must NOT trigger a build, otherwise every
      # crate would produce its own release.
      - 'v[0-9]+.[0-9]+.[0-9]+*'
"""

CHECKOUT_BLOCK = """      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive
"""

CHECKOUT_BLOCK_PATCHED = """      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive
          # Build the source of the release tag when dispatched manually.
          ref: ${{ github.event.inputs.tag || github.ref }}
"""

# cargo-dist's generated "create the release" step assumes the release must be
# created/undrafted with `--target ${{ github.sha }}`. Our single `v<version>`
# release is created by the Release-plz workflow and already points at the
# `v<version>` tag, which is (for a dispatch) an older release commit than the
# dispatched ref's HEAD. Publishing with `--target <other commit>` makes GitHub
# try to move the tag and fail with
# `HTTP 403: Resource not accessible by integration`.
CREATE_RELEASE_BLOCK = """      - name: Create GitHub Release
        env:
          PRERELEASE_FLAG: "${{ fromJson(steps.host.outputs.manifest).announcement_is_prerelease && '--prerelease' || '' }}"
          RELEASE_COMMIT: "${{ github.sha }}"
        run: |
          # If we're editing a release in place, we need to upload things ahead of time
          gh release upload "${{ needs.plan.outputs.tag }}" artifacts/*

          gh release edit "${{ needs.plan.outputs.tag }}" --target "$RELEASE_COMMIT" $PRERELEASE_FLAG --draft=false
"""

CREATE_RELEASE_BLOCK_PATCHED = """      # NOTE: manual edits below are re-applied by
      # `python3 scripts/patch_release_workflow.py` after `dist generate`.
      #
      # The single `v<version>` release is created by the Release-plz workflow,
      # pointing at the existing `v<version>` tag. dist uploaded the artifacts in
      # the step above; this step only makes sure nothing is missing and
      # publishes the release (in case it was created as a draft).
      - name: Publish GitHub Release
        env:
          PRERELEASE_FLAG: "${{ fromJson(steps.host.outputs.manifest).announcement_is_prerelease && '--prerelease' || '' }}"
        run: |
          TAG="${{ needs.plan.outputs.tag }}"

          # Upload only what is missing: `gh release upload` errors on an asset
          # that is already attached, and published assets are immutable.
          for f in artifacts/*; do
            gh release upload "$TAG" "$f" || echo "::notice::$f already attached"
          done

          # Never pass `--target`: the `v<version>` tag already exists (created
          # by the Release-plz workflow, possibly at an older release commit)
          # and GitHub rejects moving it while publishing a draft
          # ("Resource not accessible by integration").
          if [ "$(gh release view "$TAG" --json isDraft -q .isDraft)" = "true" ]; then
            gh release edit "$TAG" $PRERELEASE_FLAG --draft=false
          else
            echo "release $TAG is already published"
          fi
"""

# `github.ref_name` must become the dispatched tag when one was supplied.
#
# A run only publishes when it is a tag push or a dispatch that carries the
# `tag` input. Anything else (pull requests, and dispatches used to validate a
# release PR on its branch) runs `dist plan` only, so nothing is published.
REF_NAME_OLD = "github.ref_name"
TAG_EXPR = "(github.event.inputs.tag != '' && github.event.inputs.tag || github.ref_name)"
IS_RELEASE_EXPR = "(!github.event.pull_request && (github.event.inputs.tag != '' || github.ref_type == 'tag'))"
REF_NAME_NEW = TAG_EXPR


def replace_once(text: str, old: str, new: str, what: str) -> str:
    assert old in text, f"anchor for {what} not found; regenerate and re-run"
    return text.replace(old, new, 1)


def main() -> int:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_PATH
    text = path.read_text()

    if "workflow_dispatch:" in text:
        print(f"{path} already patched; nothing to do")
        return 0

    text = replace_once(text, ON_BLOCK, ON_BLOCK_PATCHED, "on: triggers")
    text = replace_once(text, CHECKOUT_BLOCK, CHECKOUT_BLOCK_PATCHED, "plan checkout")
    text = replace_once(
        text,
        f"tag: ${{{{ !github.event.pull_request && {REF_NAME_OLD} || '' }}}}",
        f"tag: ${{{{ {IS_RELEASE_EXPR} && {TAG_EXPR} || '' }}}}",
        "plan tag output",
    )
    text = replace_once(
        text,
        f"tag-flag: ${{{{ !github.event.pull_request && format('--tag={{0}}', {REF_NAME_OLD}) || '' }}}}",
        f"tag-flag: ${{{{ {IS_RELEASE_EXPR} && format('--tag={{0}}', {TAG_EXPR}) || '' }}}}",
        "plan tag-flag output",
    )
    text = replace_once(
        text,
        "publishing: ${{ !github.event.pull_request }}",
        f"publishing: ${{{{ {IS_RELEASE_EXPR} }}}}",
        "plan publishing output",
    )
    text = replace_once(
        text,
        f"(!github.event.pull_request && format('host --steps=create --tag={{0}}', {REF_NAME_OLD})) || 'plan'",
        f"({IS_RELEASE_EXPR} && format('host --steps=create --tag={{0}}', {TAG_EXPR})) || 'plan'",
        "dist host --tag argument",
    )
    text = replace_once(
        text,
        CREATE_RELEASE_BLOCK,
        CREATE_RELEASE_BLOCK_PATCHED,
        "Create GitHub Release step",
    )
    # The replacements themselves embed `github.ref_name` as the fallback, so
    # check that the un-substituted forms are gone instead.
    assert f"&& {REF_NAME_OLD} ||" not in text, "unpatched github.ref_name usage remains"
    assert "github.event.inputs.tag" in text, "tag input was not applied"

    path.write_text(text)
    print(f"patched {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
