#!/usr/bin/env python3
"""Re-apply local customizations to the cargo-dist generated release workflow.

`.github/workflows/release.yml` is generated by cargo-dist. We customize it
because the release is prepared by release-plz, whose tags are pushed with the
default `GITHUB_TOKEN` and therefore do not trigger workflows:

  1. Add a `workflow_dispatch` trigger with a `tag` input, so the Release-plz
     workflow can dispatch this workflow explicitly. The tag is passed as an
     input (instead of dispatching on the tag ref) because workflows are always
     read from the ref they are dispatched on, and the workflow file stored at
     an old tag's commit has no `workflow_dispatch` trigger.
  2. Restrict the tag trigger to the tags we actually publish.
  3. Use the dispatched tag (falling back to the ref) to select what dist
     builds and check out that tag's source.

Usage (after `dist generate --mode ci`):

    python3 scripts/patch_release_workflow.py [path/to/release.yml]

`dist-workspace.toml` sets `allow-dirty = ["ci"]` so cargo-dist accepts the
difference between this file and its template; re-run this script whenever the
workflow is regenerated.
"""

from __future__ import annotations

import sys
from pathlib import Path

DEFAULT_PATH = Path(".github/workflows/release.yml")

ON_BLOCK = """on:
  pull_request:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
"""

ON_BLOCK_PATCHED = """on:
  # NOTE: manual edits below are re-applied by
  # `python3 scripts/patch_release_workflow.py` after `dist generate`.
  #
  # Dispatched by the Release-plz workflow: tags pushed with the default
  # GITHUB_TOKEN do not trigger workflows. The release tag is passed as an
  # input because workflows are read from the dispatched ref, and the workflow
  # file stored at an old tag's commit may predate this trigger.
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to publish (must already exist), e.g. server-bin-v0.2.0"
        required: false
        type: string
  push:
    tags:
      # release-plz tags every package; only the dist-able ones are built here.
      - 'server-bin-v[0-9]+.[0-9]+.[0-9]+*'
      - 'v[0-9]+.[0-9]+.[0-9]+*'
"""

CHECKOUT_BLOCK = """      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive
"""

CHECKOUT_BLOCK_PATCHED = """      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive
          # Build the source of the release tag when dispatched manually.
          ref: ${{ github.event.inputs.tag || github.ref }}
"""

# `github.ref_name` must become the dispatched tag when one was supplied.
REF_NAME_OLD = "github.ref_name"
REF_NAME_NEW = "(github.event.inputs.tag || github.ref_name)"


def replace_once(text: str, old: str, new: str, what: str) -> str:
    assert old in text, f"anchor for {what} not found; regenerate and re-run"
    return text.replace(old, new, 1)


def main() -> int:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_PATH
    text = path.read_text()

    if "workflow_dispatch:" in text:
        print(f"{path} already patched; nothing to do")
        return 0

    text = replace_once(text, ON_BLOCK, ON_BLOCK_PATCHED, "on: triggers")
    text = replace_once(text, CHECKOUT_BLOCK, CHECKOUT_BLOCK_PATCHED, "plan checkout")
    text = replace_once(
        text,
        f"tag: ${{{{ !github.event.pull_request && {REF_NAME_OLD} || '' }}}}",
        f"tag: ${{{{ !github.event.pull_request && {REF_NAME_NEW} || '' }}}}",
        "plan tag output",
    )
    text = replace_once(
        text,
        f"tag-flag: ${{{{ !github.event.pull_request && format('--tag={{0}}', {REF_NAME_OLD}) || '' }}}}",
        f"tag-flag: ${{{{ !github.event.pull_request && format('--tag={{0}}', {REF_NAME_NEW}) || '' }}}}",
        "plan tag-flag output",
    )
    text = replace_once(
        text,
        f"format('host --steps=create --tag={{0}}', {REF_NAME_OLD})",
        f"format('host --steps=create --tag={{0}}', {REF_NAME_NEW})",
        "dist host --tag argument",
    )
    # The replacements themselves embed `github.ref_name` as the fallback, so
    # check that the un-substituted forms are gone instead.
    assert f"&& {REF_NAME_OLD} ||" not in text, "unpatched github.ref_name usage remains"
    assert "github.event.inputs.tag" in text, "tag input was not applied"

    path.write_text(text)
    print(f"patched {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
