[package]
name = "db"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core-domain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
sea-query = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
