name: Build Rust

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  TARGET: x86_64-unknown-linux-gnu

jobs:
  build:
    name: Build server binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Build server binary
        run: cargo build --locked --release -p server-bin --target "$TARGET"